### ISSUE TITLE
Problem window ... annoying!

### ISSUE THREAD

**Issue by ramzydoni** [B00merang-Project/Windows-10#106]
hey I'm new to Linux. I'm having a problem with the window Ubuntu distribution.
*When you click Exit for example in Windows 10 there is no problem
*But when you click in Linux there is a space. Sometimes I concentrate to press this exit ! inconvenient and annoying
http://i.imgur.com/kuVqCMO.png
Please fix problem this Theme Windows 10 helped me to move to Linux thanks you team <3

**Comment by Elbullazul** [comment]
@ramzydoni thanks for the report. It's a margin issue inherited from the original theme. I will fix this very soon.

**Comment by imranmunshi** [comment]
I actually don't see that as a problem, in fact I started using this theme because it had a margin between window edge and close button. This prevents me from accidentally closing an important window when accidental clicks/touches are struck at the top right edge.

It is more of a personal preference. I would recommend to keep it as a feature, or just doecument it in the README on how to change it in case if it's possible
