### ISSUE TITLE
Windows-10 on Cinnamon Spices

### ISSUE THREAD

**Issue by smurphos** [B00merang-Project/Windows-10#126]
@Elbullazul 

https://github.com/B00merang-Project/Chrome-OS/issues/22

The only problem I've seen with the version Windows-10 theme at https://github.com/linuxmint/cinnamon-spices-themes/tree/master/Windows-10 is that Cinnamon 3.8 won't support the version 1 Metacity theme.

But noting you are actively maintaining the theme here it would be good if you could raise a PR to bring the spices version up to date ;-)

Cheers...

**Comment by Elbullazul** [comment]
@smurphos oh, so that's why some other metacity themes didn't work. I wasn't aware that metacity themes had target versions. Anyways, will update in the coming days to newest metacity theme.

I don't like the spices update model, that's why I rarely update it over there. Maybe I'll update it this week or next month.

**Comment by Elbullazul** [comment]
Update: we won't be updating themes on Cinnamon spices anymore

**Comment by smurphos** [comment]
Any objection if I keep the Spices version up to date with your upstream? Or would you prefer for them to be removed?
