### ISSUE TITLE
XFCE Dark Version Title Close button

### ISSUE THREAD

**Issue by truefriend-cz** [B00merang-Project/Windows-10#155]
Hi. I have problem on XFCE.
If in Dark version maximized Window then Close button is from end monitor with spacing.

**Comment by Elbullazul** [comment]
can you post a screenshot of the issue ?

**Comment by truefriend-cz** [comment]
https://imgur.com/a/z6Sb7Vn

**Comment by Elbullazul** [comment]
so the bug is the right offset? It's been fixed: https://github.com/B00merang-Project/Windows-10-Dark/commit/e13805c0b3e8147717780b1cec4823713785fe51

By the way, if any bug with the dark theme happens in the future, please open a ticket in the [dark theme repo](https://github.com/B00merang-Project/Windows-10-Dark/issues)

Thanks for your feedback
