### ISSUE TITLE
[xfce] active/inactive tabs in some apps are not distinguishable enough

### ISSUE THREAD

**Issue by thekomer** [B00merang-Project/Windows-10#159]
S subject suggests, in some apps active tab is not distinguishable enough from inactive ones. At the first glance, I cant see which one is active. Productivity suffers. Look at these screenshots:
Firefox:
![firefox](https://user-images.githubusercontent.com/17909481/61190377-b2b72700-a69b-11e9-8c05-5fdf801e126c.png)
Geany:
![geany](https://user-images.githubusercontent.com/17909481/61190382-bcd92580-a69b-11e9-8b1b-09dc4b7ba4de.png)
Xfce4 terminal:
![terminal](https://user-images.githubusercontent.com/17909481/61190385-c5316080-a69b-11e9-9b33-d95a486fad2e.png)

Xfce version I use is 4.12.3 (default in debian stable)

**Comment by Elbullazul** [comment]
90e1ab2 adds more contrast:

![image](https://user-images.githubusercontent.com/15310985/61216162-a8684d80-a6da-11e9-8796-b19ed016ec1e.png)

for firefox I recommend using the 'light' theme in the customize window, because since the titlebar is white, all tabs will be white. With light on it will look something like this:

![image](https://user-images.githubusercontent.com/15310985/61216038-6e974700-a6da-11e9-8d12-63c33772c30e.png)

**Comment by thekomer** [comment]
Thank you! This is better. I don't know how Windows 10 looks like because I use Linux ;-) But maybe, if it somehow fits to it's design, maybe you could (as an addition to this change) make title (text color) for un-selected tabs a bit pale. That would make selected tab stick out even more.
If that change would  clash with your design pattern.. forget about it :-)

**Comment by Elbullazul** [comment]
something like this?

![image](https://user-images.githubusercontent.com/15310985/61242129-f4cf7f80-a712-11e9-9f2e-342230ecda4a.png)

**Comment by thekomer** [comment]
Yeah, I think it's better. Don't you? :-)

**Comment by Elbullazul** [comment]
7f6ea27 pushed ;)

**Comment by thekomer** [comment]
Great! Tnx! :-)
