### ISSUE TITLE
Dash to panel and Arc Menu enhancements

### ISSUE THREAD

**Issue by ShadowWarfare** [B00merang-Project/Windows-10#171]
The Windows 10 theme looks nice on Cinnamon however for those of us who want to use it with vanilla GNOME but with the dash to panel and the Arc Menu extension the theme itself doesn't work at all with both extensions and/or doesn't look correct. Is it possible a fix could be made for GNOME users that uses dash to panel and the Arc menu extension please? The theme itself on those extension is broken.

**Comment by ImpWarfare** [comment]
![Screenshot from 2020-02-03 21-48-37](https://user-images.githubusercontent.com/29409500/73693982-1acc6980-46cf-11ea-9979-7d8f014683bb.png)
![Screenshot from 2020-02-03 21-49-14](https://user-images.githubusercontent.com/29409500/73693992-20c24a80-46cf-11ea-9ed5-e51cd5de58e0.png)

Here's the screenshots of both extensions in use, hope it helps!

**Comment by Elbullazul** [comment]
I see the menu entry is broken and that the menu should probably be different, but what else would you change? I don't see that many differences

**Comment by ImpWarfare** [comment]
Is it possible for the Arc Menu to be fixed and if possible could the notification area with the calendar on the second image could have the same theme as the main menu etc. at the moment it uses the fallback theme and doesn't look correct with the Windows 10 theme its almost as if the Windows 10 isn't fully compatible with GNOME fully with different layouts. On another note as an addition could you make this theme compatible with Zorin OS so that we can use it on Zorin if that's possible.

**Comment by Elbullazul** [comment]
the entry was fixed. Support for Arc menu will not be added, since the extension was discontinued
