### ISSUE TITLE
how to get the taskbar in gnome?

### ISSUE THREAD

**Issue by techno2088** [B00merang-Project/Windows-10#67]
hi, i'm really sorry if this is a noob question but when apply the theme how can i get the taskbar + start menu on gnome 3 ??
i'm using gnome Version 3.16.2 on opensuse leap 42.1 64bit.

**Comment by feren** [comment]
I think @Elbullazul uses a GNOME Plugin called Dash To Dock on his GNOME screenshots, I think there's a Side-to-side mode in it's Settings, anyway, since you're a noob, here's some instructions:
1. Make sure GNOME Tweaks or GNOME Tweak Tool is in your application launcher, if not, install it
2. Run GNOME Tweaks and make sure you go to 'Extensions' in the window
3. Make sure 'User Themes' is on (then you can give GNOME the Windows 10 theme)
4. Hit 'Get New Extensions'
5. Search on the page you get in Firefox 'Dash To Dock'
6. Find it, and then turn it on from the page
7. Close and Open Tweaks again
8. Go back to Extensions and hit the cog next to 'Dash To Dock'
9. In the window that appears, experiment as you want until you get the look you desire...

**Comment by feren** [comment]
Also, if you want an easier way in the future, consider looking at Zorin OS 12 when it's released, it features a fork of GNOME 3 to look more like Windows 7/XP but should work well with the Windows 10 theme, even if it means that you're using an Ubuntu Distribution...

**Comment by brandleesee** [comment]
@feren I think we should find your list a place in the tutorials & how-to.... XD

@techno2088 some screenshots to accompany the list above

![image](https://cloud.githubusercontent.com/assets/12674437/18519898/d9ed7a6a-7aa5-11e6-9df6-382f756c8410.png)
gnome-tweak-tool

![image](https://cloud.githubusercontent.com/assets/12674437/19831385/e5937d52-9e08-11e6-9961-a0d0a4b2b162.png)
Dash-to-dock [URL](https://micheleg.github.io/dash-to-dock/download.html)

**Comment by techno2088** [comment]
thanks for your answers and I’m not a noob I’ve already tried 'Dash To Dock' before but i didn't get the results i was looking for i think TaskBar is a better solution for a person looking for a usable taskbar that show all open windows, 
any way thanks for the tip on Zorin OS.
